### ISSUE TITLE
Upgrade to Filament 3

### ISSUE THREAD

**Issue by buzkall** [intrepidws/alfred-filament-docs#1]
Hi,
Would you consider to update the plugin to the v3 docs?
Thanks!

**Comment by ariStridely** [comment]
Hey, a solution like the one adopted [here](https://github.com/tillkruss/alfred-laravel-docs/blob/main/laravel.php) would be much appreciated!
Thanks!

**Comment by intrepidws** [comment]
I just released a new version that supports 3.x, 2.x and 1.x docs searching. You can download the Alfred workflow file here:

https://github.com/intrepidws/alfred-filament-docs/releases/download/v2.0.0/Filament.Docs.alfredworkflow
